### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR ID
GET http://localhost:1234/movies/9423c9a2-9315-11f0-83d5-6c02e07770b2

### RECUPERAR UNA PELICULA POR GENERO TERROR
GET http://localhost:1234/movies?genre=Terror

### RECUPERAR UNA PELICULA POR GENERO ACTION
GET http://localhost:1234/movies?genre=actiOn


### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Drama", "Crime"],
    "rate": 8.8
}

### ACTUALIZAR UNA PELICULA
PATCH http://localhost:1234/movies/7f1acfa3-9326-11f0-83d5-6c02e07770b2
Content-Type: application/json

{
    "year": 2000,
    "duration": 210
}

### ELIMINAR UNA PELICULA
DELETE http://localhost:1234/movies/c5fbdbf3-9325-11f0-83d5-6c02e07770b2