### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR ID
GET http://localhost:1234/movies/94c04668-28c7-444e-a7ea-ed380594eab6

### RECUPERAR UNA PELICULA POR GENERO TERROR
GET http://localhost:1234/movies?genre=Terror

### RECUPERAR UNA PELICULA POR GENERO ACTION
GET http://localhost:1234/movies?genre=actiOn


### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Drama", "Crime"],
    "rate": 8.8
}

### ACTUALIZAR UNA PELICULA
PATCH http://localhost:1234/movies/047159ee-254e-4ddf-83f7-ccd793e3e316
Content-Type: application/json

{
    "year": 1995,
    "duration": 190
}

### ELIMINAR UNA PELICULA
DELETE http://localhost:1234/movies/047159ee-254e-4ddf-83f7-ccd793e3e316