### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR ID
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### RECUPERAR UNA PELICULA POR GENERO TERROR
GET http://localhost:1234/movies?genre=Terror

### RECUPERAR UNA PELICULA POR GENERO ACTION
GET http://localhost:1234/movies?genre=actiOn


### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Drama", "Crime"],
    "rate": 8.8
}

### ACTUALIZAR UNA PELICULA
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1998
}

### ELIMINAR UNA PELICULA
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1998
}